version: '3.6'
services:
  app:
    image: twoweb:talesapp
    build:
      context: .
    container_name: talesapp
    command: ['bundle', 'exec', 'rails', 'server', '-b', '0.0.0.0']
    networks:
      - talesapp-net
    volumes:
      - ".:/usr/src/app"
    ports:
      - 3000:3000
    links:
      - db
    depends_on:
      - db
  db:
    image: mysql:5
    container_name: db
    networks:
      - talesapp-net
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    
      
networks:
  talesapp-net:
    driver: bridge

volumes:
  mysql: